### ISSUE TITLE
Tools + leather doesn't seem to upgrade the attack speed?

### ISSUE THREAD

**Issue by justhalf** [Athlaeos/ValhallaMMO_open#2]
Adding leather to tools (swords, pickaxe, axe) is supposed to increase the attack speed. However, the displayed value seems to stay the same (-2.8 Attack Speed for my iron pickaxe and -2.4 Attack Speed for my Iron Sword).

Is this simply a display bug, or does the attack speed actually not change?

Stone axe before leather
![Stone axe before leather](https://github.com/Athlaeos/ValhallaMMO_open/assets/539150/2e37e279-080f-47de-a0fc-5f7af400c4fd)

Stone axe after leather
![Stone axe after leather](https://github.com/Athlaeos/ValhallaMMO_open/assets/539150/bb53bc0c-1585-4eec-9cdd-98a98ecb479e)

**Comment by Athlaeos** [comment]
this is actually currently intention, all be it poorly communicated. there is a "minimum attack speed" setting in this recipe, and if you simply don't have the skill to reach beyond that minimum then attack speed won't change. normally attack speed is reduced a little, so once you get more skilled at smithing you'll see your attack speed improve a little. sorry for the late response btw, i didnt get a notification
